### ISSUE TITLE
Cant Unapply 

### ISSUE THREAD

**Issue by illumkhan** [devansingaram/tribehired#196] opened 2013-04-04 11:11 UTC
Drew to work on it :).

**Comment by ykgoon** [comment] 2013-04-08 05:22
@illumkhan is this a duplicate of https://github.com/devansingaram/tribehired/issues/180 ?

If so, it's been fixed.

**Comment by illumkhan** [comment] 2013-04-08 07:56
The apply button goes huge and cant click on it as well.

![image](https://f.cloud.github.com/assets/2082445/350531/b6efe816-a021-11e2-85bc-6d095dbe3fae.png)

**Closed as completed** 2013-04-25 08:06 UTC
Labels: bug, priority
